### ISSUE TITLE
代码中不小心把包名改了，还请及时改回来，避免影响大家使用

### ISSUE THREAD

**Issue by xiangjihan** [hyperf-extension/auth#3]
@angeltxwh 大佬，如果你能看到消息，麻烦及时合并一下我最新的那个请求。之前为了方便使用，我用了自己的包名和地址，现在既然看到还在继续维护，所以还是会帮着维护这边的代码。

**Comment by angeltxwh** [comment]
已经处理好了@xiangjihan
